# Generated by Django 2.2.5 on 2019-09-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_superhero_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superhero',
            name='power',
        ),
    ]
